### ISSUE TITLE
Compatibility with current master branch of Godot (future Godot 4.0)

### ISSUE THREAD

**Issue by JulienVanelian** [awkwardpolygons/awkpol1#13]
As Godot 4.0 approaches, do you have an ETA to when this plugin will be compatible with the master branch of Godot?

**Comment by arccoza** [comment]
There is a new version in the pipeline for 3.x with much larger terrain support. I have already spent a little time with 4.0, and with all the new features available (glsl shaders and access to tessellation), I recon there is good reason to do a major update. But I'd like to wait for 4.0 stable before starting any work.

**Comment by JulienVanelian** [comment]
Okay, thanks for the answer!
