### ISSUE TITLE
Unable to load addon script from path: 'res://addons/cartographer/plugin.gd'

### ISSUE THREAD

**Issue by ghost** [awkwardpolygons/awkpol1#2]
Unable to load addon script from path: 'res://addons/cartographer/plugin.gd' There seems to be an error in the code, please check the syntax.

error(4,1) Expected a constant expression

const Action = Cartographer.action

**Comment by arccoza** [comment]
Are you on Godot 3.2.2?
Just replace `const` with `var` and it should be fine. Will check and update later.

**Comment by ssj17vegeta** [comment]
On Godot 3.2.2, resolved by adding cartographer_singleton.gd as Singleton with autoload = true, same as in the example project.

**Comment by ghost** [comment]
Thanks

**Comment by arccoza** [comment]
Thanks @ssj17vegeta
