### ISSUE TITLE
GPU clipmap: does it make a difference in Godot 3?

### ISSUE THREAD

**Issue by Zylann** [awkwardpolygons/awkpol1#4]
Knowing Godot 3 doesn't expose any form of tessellation, geometry shaders or index buffer tricks, I discarded doing clipmaps on the GPU in my plugin. I was surprised to see that your plugin apparently does something like that, however... is it really making a difference?
From what i see in the shader, you only displace vertices. So they always get processed, wether or not you change their position to visually merge them.
I know you can discard a vertex and all triangles using it by outputting a NaN though, which I use for grass, just never considered for LOD (I use a CPU-side quad tree instead so geometry doesnt even get to the shader). If you use that, do you have some profiling results showing how much it improves framerate?

**Comment by arccoza** [comment]
That is a good question.
Apologies for my slow response, we're in the middle of a move.

> Knowing Godot 3 doesn't expose any form of tessellation, geometry shaders or index buffer tricks, I discarded doing clipmaps on the GPU in my plugin.

Clipmaps have been around longer than tessellation and geometry shaders, solving the LOD problem before those were options. Though using them together adds even finer LOD.

> From what i see in the shader, you only displace vertices. So they always get processed, wether or not you change their position to visually merge them.
I know you can discard a vertex and all triangles using it by outputting a NaN though, which I use for grass, just never considered for LOD (I use a CPU-side quad tree instead so geometry doesnt even get to the shader).

This is the point, getting the GPU to do the work. All the vertices do run on the GPU at once. A very small mesh is passed to the GPU, then instanced as needed to expand the terrain. Each instance has the same number of vertices, but covers 4x as much area as the previous instance. So the total vertices for a very large area are actually relatively low.

Your quad tree approach and this clipmap approach are doing basically the same thing; moving and culling vertices/triangles where they are needed (following the camera), while keeping the average total number of vertices relatively low. The major difference is that the clipmap uses the GPU to move vertices around, and clip any unneeded (reducing the eventual load on the fragment shader). This is the GPU's wheelhouse, manipulating vertices.

> If you use that, do you have some profiling results showing how much it improves framerate?

If I use NaN / Inf vertex discarding to improve performance? I clip vertices that go out of bounds, and the unneeded center surface when doing each instance of the clipmap (this could be avoided, but I'm constrained by what I can do in a Godot shader). As for performance, discarding unneeded triangles should improve fragment shader load, but no testing yet.

> is it really making a difference?

Ultimately this is the theory, and it does appear to be, but I haven't done any real profiling, concentrating on getting basic features done before fine tuning performance. If you'd like to help test the waters, that'd be great. Either way, I promise I'll do some thorough profiling once I've hit all the basic goals.

As a side note; thanks for all your work around Godot, it's been very helpful.

**Comment by Zylann** [comment]
> A very small mesh is passed to the GPU, then instanced as needed to expand the terrain. Each instance has the same number of vertices, but covers 4x as much area as the previous instance

So that's the part I've been doing on CPU, using `MeshInstance`. The "instance as needed" is done by the quadtree, then I do the stitching by switching between premade versions of that small mesh with various border configurations, then displace vertices in vertex shader.

> I clip vertices that go out of bounds, and the unneeded center surface when doing each instance of the clipmap (this could be avoided, but I'm constrained by what I can do in a Godot shader).

So it seems your approach is actually very different than mine. Do you mean that you have a single mesh per LOD, and discard the center part of each "concentric" planes to fit the higher-LOD ones? Are each LODs represented by one single mesh, or do you chunk them to take advantage of frustum culling? I'm not sure if I'm clear^^

I did not use a technique using vertex discarding mostly because otherwise it would mean instancing a single huge plane, or several huge planes of fixed size, which either make frustum culling useless or are not scalable due to their fixed size, and more or less come back to a quadtree approach to some extent, with the features available to us. Unless I'm missing some solving details about GPU-based clipmaps when applied to Godot.

**Comment by arccoza** [comment]
That's the gist of it, I need to write a clearer explanation. Frustum culling is possible, but I haven't implemented it in my simplified clipmap implementation. Most other implementations that I read of said that the benefits of frustum culling are small and mostly outweighed by the complexity of including it. So for now I've skipped it.

**Comment by arccoza** [comment]
![pg1](https://user-images.githubusercontent.com/604119/89883182-c4eaf800-dc02-11ea-9d59-9f10f7be6f86.png)
![pg2](https://user-images.githubusercontent.com/604119/89883189-c7e5e880-dc02-11ea-9ea4-99f65f9f0d13.png)
![pg3](https://user-images.githubusercontent.com/604119/89883197-c9afac00-dc02-11ea-8a5c-66782003164a.png)
![pg4](https://user-images.githubusercontent.com/604119/89887103-b273bd00-dc08-11ea-898d-855c35cfd94e.png)
![pg5](https://user-images.githubusercontent.com/604119/89887112-b43d8080-dc08-11ea-94c1-47bd18420c97.png)
![pg6](https://user-images.githubusercontent.com/604119/89893411-421e6900-dc13-11ea-941c-ceab5cf84478.png)

There is plenty of room for improvement, but for now this simplified implementation works well. A full clipmap implementation involves many small meshes, including smaller filler meshes to help plug gaps and align the different pieces as the clipmap moves.
