### ISSUE TITLE
Plugin fails to load due to syntax error.

### ISSUE THREAD

**Issue by EzraT** [awkwardpolygons/awkpol1#5]
OS: Linux Mint 20 x86_64
Plugin version: 0.7.0
Godot version: 3.2.2.stable

Whenever I try to enable Cartographer in the plugins menu, Godot displays the following pop-up error message:
![image](https://user-images.githubusercontent.com/781121/87873214-fab00e80-c9bf-11ea-90b4-99d00eac59f8.png)

And the following console output:
![image](https://user-images.githubusercontent.com/781121/87873235-1b786400-c9c0-11ea-99a0-60246119c2d1.png)

Thanks in advance, this plugin looks great!

**Comment by arccoza** [comment]
You need to enable the cartographer [singleton](https://docs.godotengine.org/en/stable/getting_started/step_by_step/singletons_autoload.html). Check the example's settings. I should add this to the readme.

**Comment by EzraT** [comment]
> You need to enable the cartographer [singleton](https://docs.godotengine.org/en/stable/getting_started/step_by_step/singletons_autoload.html).

Thanks, I tried that before and it gave me the same error, but I see where things went wrong now, the project needs to be reloaded after the singleton is added, after that the plugin loads.

I'm a bit confused though, isn't the plugin supposed to add the singleton on init by itself?
The init function of the plugin.gd tries to load it with: 
`add_autoload_singleton("Cartographer", "res://addons/cartographer/cartographer_singleton.gd")`

What use does this have if you need to load it manually anyway?

**Comment by arccoza** [comment]
`add_autoload_singleton` just adds it to the autoload list, you still have to enable it, as for the reasoning, I don't know.
