### ISSUE TITLE
Tile Breaker Plugin

### ISSUE THREAD

**Issue by wojtekpil** [awkwardpolygons/awkpol1#6]
There was recently created a very cool plugin for a Godot: https://github.com/SIsilicon/Tile-Breaker-Plugin I think, that its integration would dramatically improve a texturing quality. I don't know anything about the performance impact, but it's worth a try.

**Comment by arccoza** [comment]
Yeah, looks great, I've seen similar projects for Unreal. I wonder how well it works with more regular/geometric pattern textures, like bricks.
