### ISSUE TITLE
Can't open example project

### ISSUE THREAD

**Issue by jocamar** [awkwardpolygons/awkpol1#9]
Can't get the example project to work in Godot 3.2.4 RC4. It complains about missing dependencies (e.g. no res://example/textures folder).

**To Reproduce**
1. Download zip of the repo
2. Import project.godot into godot
3. Open project and try to open any of the scenes

**Expected behavior**
Project should open correctly and show the addon in action.

**Screenshots**
![image](https://user-images.githubusercontent.com/4234276/111226987-ce45a400-85d9-11eb-8ec2-4d3fd5977cc8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Godot Version 3.2.4 RC4
 - Cartographer Version 0.9.0

**Comment by jocamar** [comment]
Also doesn't work with downloading the zip from the releases.

**Comment by arccoza** [comment]
Did you download the texture assets pack linked to in the release notes?

**Comment by jocamar** [comment]
Ah, should've RTFM. Thanks!

**Comment by arccoza** [comment]
No worries.
